version: '1.0.0'
services:
    redis:
        image: 'redis:3.2.7'

    mysql:
        image: mysql:5.7
        container_name: airflow_db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=airflow
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci


    webserver:
        image: sathraje/docker-airflow
        container_name: airflow_webserver
        restart: always
        depends_on:
            - mysql
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: sathraje/docker-airflow
        container_name: airflow_flower
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: sathraje/docker-airflow
        container_name: airflow_scheduler
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: scheduler

    worker:
        image: sathraje/docker-airflow
        container_name: airflow_worker
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: worker
